/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AlunoController;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Aluno;

/**
 *
 * @author NathaliaCosim
 */
public class FrmListaAluno extends javax.swing.JInternalFrame {
    List<Aluno> list = new ArrayList<Aluno>();
    AlunoController ac = new AlunoController();
    /**
     * Creates new form FrmListaAluno
     */
    public FrmListaAluno() {
        initComponents();
        list = ac.getAlunos();
        preencheTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbAlunos = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Lista de Alunos");

        tbAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Sexo", "Idade", "Peso", "Telefone", "Email", "Endereco"
            }
        ));
        jScrollPane1.setViewportView(tbAlunos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbAlunos;
    // End of variables declaration//GEN-END:variables

    public void preencheTabela() {
        tbAlunos.getColumnModel().getColumn(0).setPreferredWidth(20);
        DefaultTableModel modelo = (DefaultTableModel) tbAlunos.getModel();
        modelo.setNumRows(0);
        for (int i = 0; i < list.size(); i++) {
            modelo.addRow(new Object[]{list.get(i).getId(), list.get(i).getNome(),
            list.get(i).getSexo(), list.get(i).getIdade(), list.get(i).getPeso(),
            list.get(i).getTelefone(),list.get(i).getEmail(),list.get(i).getEndereco()});
        }
    }
    
    public void centralizarComponente() { 
        Dimension ds = this.getDesktopPane().getSize();
        setLocation((ds.width - this.getSize().width) / 2, (ds.height - this.getSize().height) / 5); 
    }
}
